version: "3"

services:
  frontend:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./streamlit/src:/app/src
    command: streamlit run /app/src/main.py --server.port=8501 --server.address=0.0.0.0
    networks:
      - vannaai-network

  ollama-llm:
    image: ollama/ollama:latest
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
    networks:
      - vannaai-network

networks:
  vannaai-network:
    external: false
